### ISSUE TITLE
airlock Erro Code 420

### ISSUE THREAD

**Issue by JhonGdl** [drawrowfly/airbnb-private-api#2]
I'm having some problem in the authentication.

Error:  { type: 'StatusCodeError',
  error_code: 420,
  error: 'unknown_error',
  error_message:
   'Unable to perform action. Please try again through the website or contact support if you need immediate assistance.',
  client_error_info:
   { airlock:
      { action_name: 'account_login',
        completion_redirect_url: '',
        error_redirect_url: '',
        escapable: true,
        fallback_friction: 'contact_us_form',
        flow: 'captcha_flow',
        friction_data: [Array],
        header_text: 'Please verify yourself',
        id: 5397911699,
        keep_webview_open_on_redirect: false,
        redux: true,
        status: 0,
        should_replay_request: true,
        airlockId: '5397911699' } } }

**Comment by drawrowfly** [comment]
flow: 'captcha_flow'

You can try to solve it manually from the browser and it can whitelist your ip for future use or yo can Try to login by using Phone

**Comment by d668** [comment]
I am logged in in browser on the same IP 
`Object {type: "StatusCodeError", error_code: 420, error: "unknown_error", error_message: "Unable to perform action. Please try again through…", client_error_info: Object}`

naive to think you can sniff some requests and not get stopped

**Comment by d668** [comment]
Actually after logging out and back in ` airbnb._authentication_by_email();` worked.

**Comment by d668** [comment]
420 again

**Comment by drawrowfly** [comment]
Well if it is crap then don't use it. It probably needs an update . I will look at it soon

**Comment by d668** [comment]
ok sorry i edited the comment actually, well hope we can do something
