### ISSUE TITLE
Meaning of `include_checkpoint`

### ISSUE THREAD

**Issue by kratam** [drawrowfly/airbnb-private-api#3]
Hi,

can someone explain what does `include_checkpoint` means? 
`accepted`: the reservation is active and accepted by the host (or it's an instant booking)
`canceled`: canceled by the guest, host or admin
`pending`: i'm not 100% sure, but probably: guest sent an inquiry and waiting for an answer
...?

**Comment by drawrowfly** [comment]
Hi,

Well, i believe this is related to the addition account verification and etc
